name: Update README

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at 00:00

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install github-profile-maker
    - name: Update README
      run: |
        python -m github_profile_maker vinmeil
    - name: Commit and push if changed
      run: |
        git diff
        git config --global user.email "vincent.wesley.liem@gmail.com"
        git config --global user.name "Vincent Liem"
        git commit -am "Updated README" || exit 0
        git push
